#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 19 20:36:01 2021

@author: user
"""


    def has_flush(self):
        """Checks whether this hand has a flush."""
        for val in self.suitshist.values():
            if val >= 5:
                return True
        return False
    
    def no_flush(self):
        for val in self.suithist.values():
            if val < 5:
                return True
        return False
    
class Hist(dict):
    """A map from each item (x) to its frequency."""

    def __init__(self, seq=[]):
        "Creates a new histogram starting with the items in seq."
        for x in seq:
            self.count(x)

    def count(self, x, f=1):
        "Increments the counter associated with item x."
        self[x] = self.get(x, 0) + f
        if self[x] == 0:
            del self[x]
def eval(self):
        self.rnum = [ self.numbers.count(i) for i in self.numbers]
        self.rlet = [ self.suits.count(i) for i in self.suits]
        self.dif = max(self.numbers) - min(self.numbers)
        self.p=[0,0,0,0,0] #parameters for different handtypes
        
        self.suithist = Hist()
        self.numhist = Hist()
        
        for c in self.hand:
            self.suithist.count(c.suit)
            self.numhist.count(c.value)

        self.sets = list(self.numhist.values())  #dict 的函數
        self.sets.sort(reverse=True)
        self.suitset = list(self.suithist.values())
        self.suitset.sort(reverse=True)
    
       def check_sets(self, *t):
        for need, have in zip(t, self.sets): #這招特別 因為sort過
            if need > have: return False
        return True
    
    #for precise match of *t not >
    def check_sets2(self, *t):
        for need, have in zip(t, self.sets): #這招特別 因為sort過
            if need != have: return False
        return True
    
    def check_suitset(self, *t):
        for need, have in zip(t, self.suitset): #這招特別 因為sort過
            if need > have: return False
        return True
    
    def has_pair(self):
        """Checks whether this hand has a pair."""
        return self.check_sets(2)
        
    def has_twopair(self):
        """Checks whether this hand has two pair."""
        return self.check_sets(2, 2)
    
    def has_threekind(self):
        """Checks whether this hand has three of a kind."""
        return self.check_sets(3)
        
    def has_fourkind(self):
        """Checks whether this hand has four of a kind."""
        return self.check_sets(4)

    def has_fullhouse(self):
        """Checks whether this hand has a full house."""
        return self.check_sets(3, 2)
    
       #wrong algo
    def no_straight(self):
        return( not self.has_straight())
           
            
        
    def has_straight(self):
        """Checks whether this hand has a straight."""
        # make a copy of the rank histogram before we mess with it
        ranks = self.numhist.copy()
        ranks[1] = ranks.get(14, 0) #把 A 調到前面當 1
        # see if we have 5 in a row
        return self.in_a_row(ranks, 5)
    
    
    def in_a_row(self, ranks, n=5):
        """Checks whether the histogram has n ranks in a row.
        hist: map from rank to frequency
        n: number we need to get to
        """
        count = 0
        for i in range(1, 15):
            if ranks.get(i, 0):
                count += 1
                if count == n:
                    return i  #return highest num of the straight
            else:
                count = 0
        return 0
    