#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep  9 10:30:17 2021

@author: user
"""

import sys
import random
import numpy as np
import pandas as pd
import itertools
from itertools import product
import more_itertools
import math

class Card(object):
    def __init__(self, suit, val):
        self.suit = suit
        self.value = val

    # Implementing build in methods so that you can print a card object
    def __unicode__(self):
        return self.show()
    def __str__(self):
        return self.show()
    def __repr__(self):
        return self.show()
        
    # A=14, and suit first
    def show(self):
        suits = {"H":"♡", "S":"♠", "D":"♢", "C":"♣"}
        values = {**{i:str(i) for i in range(2,11)}, 
                 **{ 11:'J',12:'Q', 13:'K', 14:'A'}}
        return suits[self.suit]+values[self.value]
    
    def letter(self):
        return(self.value)
    
    def suit(self):
        return(self.suit)
    
    def isBlack():
        return self.suit == "C" or self.suit=="S"
    
    def isRed():
        return self.suit == "D" or self.suit=="H"

class Deck(object):
    def __init__(self):
        self.cards = []
        self.build()

    # Display all cards in the deck
    def show(self):
        i=0
        for card in self.cards:
            i+=1
            print (card.show())
            if i%13==0 :
                print ('\n')

    # Generate 52 cards
    def build(self):
        self.cards = []
        numbers=list(range(2,15))
        suits = ['C','D','H','S']
        deck = []
        for i in numbers:
            for s in suits:
                #card = "{:0>2d}".format(i)+s
                self.cards.append(Card(suit, i))
    
        #for suit in ['C', 'D', 'H', 'S']:
        #    for val in range(1,14):
        #        self.cards.append(Card(suit, val))

    # Shuffle the deck
    def shuffle(self, num=1):
        length = len(self.cards)
        for _ in range(num):
            # This is the fisher yates shuffle algorithm
            for i in range(length-1, 0, -1):
                randi = random.randint(0, i)
                if i == randi:
                    continue
                self.cards[i], self.cards[randi] = self.cards[randi], self.cards[i]
    
    # You can also use the build in shuffle method
    # random.shuffle(self.cards)
    def shuffle2(self,num=1):
        random.shuffle(self.cards)

    # Return the top card
    def deal(self):
        return self.cards.pop() #取出list最後一個元素並且移除
    
class Player(object):
    def __init__(self, name, hand=[]):
        self.name = name
        self.hand = hand

    def sayHello(self):
        print ('Hi! My name is {}'.format(self.name))
        return self

    # Draw n number of cards from a deck
    # Returns true in n cards are drawn, false if less then that
    def draw(self, deck, num=1):
        for _ in range(num):
            card = deck.deal()
            if card:
                self.hand.append(card)
            else: 
                return False
        return True

    # Display all the cards in the players hand
    def showHand(self):
        print ("{}'s hand: {}".format(self.name, self.hand))
        return self

    def discard(self):
        return self.hand.pop()

#object for a general hand of cards
class Hand(object):
    def __init__(self,hand):
        self.hand = sorted(hand)
        self.handsize = len(hand)
        self.letters = [hand[i].letter() for i in range(self.handsize)]
        self.numbers = [hand[i].number() for i in range(self.handsize)]
        self.rnum = [ self.numbers.count(i) for i in self.numbers]
        self.rlet = [ self.letters.count(i) for i in self.letters]
        self.dif = max(self.numbers) - min(self.numbers)

    def show(self):
        s = [ i.show() for i in self.hand ]
        #s = [ showcard(i[2:], int(i[:2])) for i in hand] 
        return(s)
    
    def isAllBlack(self):
        bb = [ i.isBlack() for i in self.hand ]
        return(all(bb))
    
    def isAllRed(self):
        rr = [ i.isRed() for i in self.hand ]
        return(all(rr))
    
    
#專屬13支一手牌的object
class Hand13(object):
    def __init__(self, hand):
        self.hand = hand
        self.htop = hand[0]
        self.hmid = hand[1]
        self.hbot = hand[2]
        self.specialhand = chk_special()
    
    def show(): #there's 3 list in hand
    for hh in self.hand:
        ss=[]
        s = [ i.show() for i in hh] 
        ss.append(s)
        return(ss)
    
    def specialhand():
        return('ok')
        
   